# Generated by Django 6.0.6 on 2026-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
