# Generated by Django 6.0.6 on 2026-07-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/'),
        ),
    ]
