# Generated by Django 6.0.6 on 2026-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_landlordverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockledger',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('ad_reward', 'Watched Ad')], default='mpesa', max_length=20),
        ),
    ]
