# Generated by Django 6.0.6 on 2026-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_tourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
