# Generated by Django 6.0.8 on 2026-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listingimage_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockledger',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]
